version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: video-management-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: video_management
      MYSQL_USER: video_management
      MYSQL_PASSWORD: video_password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "33068:3306"
    volumes:
      # Persist database data
      - mysql_data:/var/lib/mysql
      # Custom MySQL configuration
      - ./mysql/conf.d:/etc/mysql/conf.d
      # Initialization scripts
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - video-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=256M
      --max-connections=200

  # Video Management API Service
  video-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-management-api
    restart: unless-stopped
    ports:
      - "8089:8080"
    environment:
      # HikariCP configuration - FIXED for auto-commit issues
      SPRING_DATASOURCE_HIKARI_AUTO_COMMIT: false
      SPRING_DATASOURCE_HIKARI_TRANSACTION_ISOLATION: TRANSACTION_READ_COMMITTED
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 15
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 3
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 600000
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 1800000
      SPRING_DATASOURCE_HIKARI_LEAK_DETECTION_THRESHOLD: 60000

      # JPA/Hibernate configuration - FIXED for multi-tenant
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: false
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS: true
      SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_SIZE: 20
      SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_INSERTS: true
      SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_UPDATES: true
      SPRING_JPA_OPEN_IN_VIEW: false

      # Spring Transaction configuration
      SPRING_TRANSACTION_DEFAULT_TIMEOUT: 30
      SPRING_TRANSACTION_ROLLBACK_ON_COMMIT_FAILURE: true

      # Multi-tenant configuration
      MULTITENANT_DEFAULT_TENANT: video_management
      MULTITENANT_DATASOURCE_URL_PATTERN: "jdbc:mysql://mysql:3306/%s?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8"
      MULTITENANT_DATASOURCE_MAXIMUM_POOL_SIZE: 10
      MULTITENANT_DATASOURCE_MINIMUM_IDLE: 2
      MULTITENANT_DATASOURCE_CONNECTION_TIMEOUT: 30000
      MULTITENANT_DATASOURCE_IDLE_TIMEOUT: 600000
      MULTITENANT_DATASOURCE_MAX_LIFETIME: 1800000
      MULTITENANT_DATASOURCE_LEAK_DETECTION_THRESHOLD: 60000

      # Application configuration
      SERVER_PORT: 8080
      SERVER_SERVLET_CONTEXT_PATH: /

      # Jackson configuration
      SPRING_JACKSON_TIME_ZONE: Asia/Ho_Chi_Minh
      SPRING_JACKSON_DATE_FORMAT: yyyy-MM-dd HH:mm:ss

      # OAuth2 configuration
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://keycloak.openlearnhub.io.vn/realms/OpenLearnHub/protocol/openid-connect/certs

      # Policy enforcement
      POLICY_ENFORCE: /policy-enforcer.json

      # Java options
      JAVA_OPTS: "-Xms512m -Xmx1024m -XX:+UseG1GC -Dspring.profiles.active=docker"
    volumes:
      # Application logs
      - ./logs:/app/logs
      # Policy enforcer config (if you want to override)
      # - ./config/policy-enforcer.json:/app/policy-enforcer.json:ro
    networks:
      - video-network
    depends_on:
      mysql:
        condition: service_healthy

networks:
  video-network:
    driver: bridge
    name: video-management-network

volumes:
  mysql_data:
    driver: local
    name: video-management-mysql-data