server:
  port: 8080
  servlet:
    context-path: /

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://keycloak.openlearnhub.io.vn/realms/OpenLearnHub/protocol/openid-connect/certs
  application:
    name: video-management-api

  # DataSource configuration - sẽ được override bởi TenantAwareDataSource
  datasource:
    url: jdbc:mysql://10.8.0.1:33068/video_management?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # CRITICAL: Set auto-commit to false for Spring Transaction Management
    hikari:
      auto-commit: false
      transaction-isolation: TRANSACTION_READ_COMMITTED

  # Liquibase Configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    # Liquibase sẽ tạo table riêng để track migration history
    default-schema: ${multitenant.default-tenant:video_management}
    # Contexts để control môi trường chạy
    contexts: default
    # Database change log table name (tùy chọn)
    database-change-log-table: DATABASECHANGELOG
    database-change-log-lock-table: DATABASECHANGELOGLOCK

  jpa:
    hibernate:
      # QUAN TRỌNG: Đổi từ 'update' sang 'validate'
      # để Liquibase quản lý schema thay vì Hibernate
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        # Performance tuning cho multi-tenant
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        # CRITICAL FIX: Remove connection provider auto-commit disable
        # connection:
        #   provider_disables_autocommit: true
    open-in-view: false

  # Data JPA Auditing Configuration
  # Bật auditing để tự động set createdBy, updatedBy
  data:
    jpa:
      repositories:
        enabled: true

  # Transaction management configuration
  transaction:
    default-timeout: 30
    rollback-on-commit-failure: true

  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd HH:mm:ss

# Multi-tenant configuration
multitenant:
  # Default tenant khi không có header db
  default-tenant: video_management

  # DataSource configuration cho từng tenant
  datasource:
    # URL pattern - %s sẽ được thay thế bằng tenant ID (database name)
    # FIXED: Remove createDatabaseIfNotExist to avoid auto-commit issues
    url-pattern: "jdbc:mysql://10.8.0.1:33068/%s?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8"

    # HikariCP Connection Pool Settings
    maximum-pool-size: 10        # Tối đa 10 connections per tenant
    minimum-idle: 2              # Tối thiểu 2 idle connections
    connection-timeout: 30000    # 30 seconds timeout
    idle-timeout: 600000         # 10 minutes idle timeout
    max-lifetime: 1800000        # 30 minutes max connection lifetime
    leak-detection-threshold: 60000  # 60 seconds leak detection

# Logging configuration để monitor Liquibase
logging:
  level:
    liquibase: INFO
    com.ptit.google.veo3: DEBUG
    org.springframework.data.jpa: DEBUG
    # Bật log SQL để debug
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

policy:
  enforce: "/policy-enforcer.json"

# Application specific configuration
app:
  video:
    # Số phút timeout để tự động reset video về trạng thái chưa ai nhận
    # Mặc định 15 phút theo yêu cầu business
    assignment-timeout-minutes: 120